### ISSUE TITLE
help with adding to whats app bot

### ISSUE THREAD

**Issue by TentacleSama4254** [Zekfad/nhentai-api#9]
how do i con figure this to add to a whatsapp bot like https://github.com/SomnathDas/Whatsapp-Botto-Re

**Comment by Zekfad** [comment]
This issue seems unrelated to this repository:
You can configure API for your exact needs, for the most of time default settings are enough.
To add new features to the bot you're linked you have to contact the bot creator for the details.
I'd suggest you to inspect the code of the bot repository and implement the feature you want, basic examples how to use my module is in readme and docs.
If you want to request feature for bot, please fire it to the bot repository.

If you have more specific questions about how to use `nhentai-api` feel free to respond and I'll reopen the issue.
